name: "Deploy terraform-network"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::${{ secrets.CONTA_AWS }}:role/githubActions-network"
      aws-region: "${{ vars.AWS_REGION }}"
      aws-statefile-s3-bucket: "${{ vars.BUCKET_S3_NAME }}"
      aws-statefile-key: "network/terraform.tfstate"
      aws-lock-dynamodb-table: "${{ vars.DYNAMODB_TABLE }}"